logging:
  level:
    org.springframework: INFO
    com.king: DEBUG

################### DataSource Configuration ##########################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.252.26.228:3306/mine_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qwer1234.
    initialize: true
init-db: true

#context.listener.classes: com.king.utils.Init